pandas is a python libraries used for:

- reading data(csv,excel,etc)
- cleaning data
- analysing data
- preparing data for visualization

In [1]:
import pandas as pd

In [ ]:
#series vs dataframe
#a series is a single column of data
#it is one dimensional

In [4]:
s=pd.Series([1,2,3,4])
print(s)

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
#custom index
s=pd.Series([1,2,3,4],index=['a','b','c','d'])
print(s)

a    1
b    2
c    3
d    4
dtype: int64

In [6]:
s=pd.Series([1.1,2.5,3.7,4.9],index=['a','b','c','d'])
print(s)

a    1.1
b    2.5
c    3.7
d    4.9
dtype: float64

In [12]:
#dataframe
#a dataframe is a 2D table of data(rows+columns)
data={'name':['Alice','Bob','Charlie','David'],
      'age':[25,30,35,40],
      'city':['NY','LA','Chicago','Houston']}
df=pd.DataFrame(data)
print(df)
print(df.index)
print(df.columns)
print(df.values)

      name  age     city
0    Alice   25       NY
1      Bob   30       LA
2  Charlie   35  Chicago
3    David   40  Houston
RangeIndex(start=0, stop=4, step=1)
Index(['name', 'age', 'city'], dtype='str')
[['Alice' 25 'NY']
 ['Bob' 30 'LA']
 ['Charlie' 35 'Chicago']
 ['David' 40 'Houston']]

In [3]:
#data loading
#this is to bring data into pandas
df=pd.read_csv("North America Restaurants (1).csv")
df.head()

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
0,Burger King,Manitowoc,WI,54220,US,"American, Burger, Burgers, Family Meals, Fast ...",True,True,2.4,42
1,Petro-Canada,Airdrie,AB,T4A,CA,"Ben & Jerry's, Café/Thé, Coffee/Tea, Convenien...",True,True,4.1,1
2,Boba Bae,Ashwaubenon,WI,54304,US,"American, Asian Food, Bubble Tea, Coffee & Tea...",True,True,4.0,88
3,1001 Nights Shawarma,Kitchener,ON,N2C,CA,"Beau, Bon, Local, Chicken, Dessert, Desserts, ...",True,True,4.6,1077
4,Chirpyhut Fried Chicken (JlgJ),Richmond,BC,V6X 2B8,CA,"Ailes, Allergy Friendly, American, Beau, Bon, ...",True,True,4.6,30

In [7]:
df.head(10)
df.tail()       #last 5 rows

,name,city,state,zipcode,country,cuisines,pickup_enabled,delivery_enabled,weighted_rating_value,aggregated_rating_count
1495,Grandma's Soul Food,Richmond,VA,23234,US,"American, Burgers, Chicken, Dessert, Dinner, K...",True,True,2.0,5
1496,Jimbob's Pizza,Eau Claire,WI,54701,US,"American, Fast Food, Healthy Pizza, Ice Cream ...",False,True,4.1,127
1497,Petro-Canada,Longueuil,QC,J4V,CA,"Convenience, Everyday Essentials, Grocery, Hom...",True,True,4.5,47
1498,Denny's,Kingman,AZ,86401,US,"American, Breakfast And Brunch, Coffee And Tea...",True,True,3.4,22
1499,Bean House,Richmond Hill,ON,L4B 3Z1,CA,"Alcohol, Asian, Asian Fusion, Chinese, Dessert...",True,True,4.8,93

In [ ]:
df.info()       #summary of dataframe info of the imported file

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   name                     1500 non-null   str
 1   city                     1500 non-null   str
 2   state                    1500 non-null   str
 3   zipcode                  1500 non-null   str
 4   country                  1500 non-null   str
 5   cuisines                 1499 non-null   str
 6   pickup_enabled           1500 non-null   bool
 7   delivery_enabled         1500 non-null   bool
 8   weighted_rating_value    1500 non-null   float64
 9   aggregated_rating_count  1500 non-null   int64
dtypes: bool(2), float64(1), int64(1), str(6)
memory usage: 96.8 KB

In [9]:
df.describe()   #statistical summary of numeric columns

       weighted_rating_value  aggregated_rating_count
count            1500.000000              1500.000000
mean                3.724533                85.500667
std                 0.989005               277.071136
min                 1.000000                 1.000000
25%                 2.900000                 5.000000
50%                 4.100000                25.000000
75%                 4.600000                68.000000
max                 5.000000              4211.000000

In [12]:
#load excel file
df=pd.read_excel("Car Dashboard Source.xlsx")

In [13]:
df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,1,US-2019-103800,2019-01-03,2019-01-07,Standard Class,DP-13000,Darren Powers,Replacement,United States,Houston,Texas,77095,Central,OFF-PA-10000174,Third Party,Paper,16.448,2,0.2,5.5512
1,2,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Other,United States,Naperville,Illinois,60540,Central,OFF-BI-10004094,Third Party,Binders,3.540,2,0.8,-5.4870
2,3,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Other,United States,Naperville,Illinois,60540,Central,OFF-LA-10003223,Third Party,Labels,11.784,3,0.2,4.2717
3,4,US-2019-112326,2019-01-04,2019-01-08,Standard Class,PO-19195,Phillina Ober,Other,United States,Naperville,Illinois,60540,Central,OFF-ST-10002743,Third Party,Storage,272.736,3,0.2,-64.7748
4,5,US-2019-141817,2019-01-05,2019-01-12,Standard Class,MB-18085,Mick Brown,Replacement,United States,Philadelphia,Pennsylvania,19143,East,OFF-AR-10003478,Third Party,Art,19.536,3,0.2,4.8840
5,6,US-2019-167199,2019-01-06,2019-01-10,Standard Class,ME-17320,Maria Etezadi,Other,United States,Henderson,Kentucky,42420,South,FUR-CH-10004063,Direct Sale,Chairs,2573.820,9,0.0,746.4078
6,7,US-2019-167199,2019-01-06,2019-01-10,Standard Class,ME-17320,Maria Etezadi,Other,United States,Henderson,Kentucky,42420,South,OFF-AR-10001662,Other,Art,5.480,2,0.0,1.4796
7,8,US-2019-106054,2019-01-06,2019-01-07,First Class,JO-15145,Jack O'Briant,Servicing,United States,Athens,Georgia,30605,South,OFF-AR-10002399,Other,Art,12.780,3,0.0,5.2398
8,9,US-2019-167199,2019-01-06,2019-01-10,Standard Class,ME-17320,Maria Etezadi,Other,United States,Henderson,Kentucky,42420,South,OFF-BI-10004632,Other,Binders,609.980,2,0.0,274.4910
9,10,US-2019-167199,2019-01-06,2019-01-10,Standard Class,ME-17320,Maria Etezadi,Other,United States,Henderson,Kentucky,42420,South,OFF-FA-10001883,Other,Fasteners,31.120,4,0.0,0.3112

In [ ]:
df=pd.read_excel("Car Dashboard Source.xlsx",sheet_name="Budget")   #specfying the sheet in excel
df.head(10)

        Date     Sales
0 2019-01-06  2573.820
1 2019-01-06   755.960
2 2019-01-06   391.980
3 2019-01-07    76.728
4 2019-01-09    31.200
5 2019-01-10    51.940
6 2019-01-11     9.940
7 2019-01-13   333.999
8 2019-01-13   545.940
9 2019-01-13   646.740

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3714 entries, 0 to 3713
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3714 non-null   datetime64[us]
 1   Sales   3714 non-null   float64
dtypes: datetime64[us](1), float64(1)
memory usage: 58.2 KB

In [23]:
#without parsing sometimes date column loads as object(string)
df=pd.read_csv("Car Dashboard Source.csv",parse_dates=["Date"]) #this is to convert date column into datatype automatically
df=pd.read_csv("Car Dashboard Source.csv",parse_dates=["Date1","Date2"])    #multiple date columns parsing

FileNotFoundError: [Errno 2] No such file or directory: 'Car Dashboard Source.csv'